### ISSUE TITLE
Elm 0.17

### ISSUE THREAD

**Issue by hiaw** [pdamoc/elm-docset#6]
Hi, Thank for creating this docset. Can you update for elm 0.17? Thanks a lot

**Comment by pdamoc** [comment]
The documentation format hasn't changed and the generator works on 0.17 without modifications. 

I've created a PR with today's packages on the official Dash User Contributors repository. 

Initially I was planning to wait until the end of the week to create the first release for 0.17 since there are only about 30 packages updated for 0.17 out of more than 200.
